select
count(*),sum(RAWREVENUE)Revenue,RAWCOMPANYKEY,RAWSCENARIOKEY,CLNPRODUCTGROUPKEY,CLNSCENARIOKEY,CLNLOCATIONENTITYKEY,RAWDATEKEY,RAWCURRENCYKEY,
CLNCURRENCYKEY,UDPDATASETKEY,UDPSYSTEMKEY,UDPENTITYKEY
from {{ ref('BaseRevenue') }}
group by RAWCOMPANYKEY,RAWSCENARIOKEY,CLNPRODUCTGROUPKEY,CLNSCENARIOKEY,CLNLOCATIONENTITYKEY,RAWDATEKEY,RAWCURRENCYKEY,
CLNCURRENCYKEY,UDPDATASETKEY,UDPSYSTEMKEY,UDPENTITYKEY
having count(*)>1
